name: Dockerize

on:
  push:
    branches:
      - master
      - consortium-v2
  pull_request:
    branches:
      - master
      - consortium-v2

jobs:
  docker:
    uses: axieinfinity/workflows-samples/.github/workflows/docker-build-submodule.yml@main
    with:
      checkout_submodules: true
      image_repository: gcr.io/test-servers-256610/ronin
    secrets: inherit